# Generated by Django 5.0.3 on 2024-03-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_range', models.CharField(max_length=10)),
                ('male_population', models.IntegerField()),
                ('female_population', models.IntegerField()),
            ],
        ),
    ]
